<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use GapPay\Seguranca\Models\Entity\SegAcao;

class SegAcaoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        $items = [
            [
                'id' => 1,
                'nome' => 'api/login',
                'method' => 'POST',
                'descricao' => 'Api que faz login do usuário',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => true,
                'grupo' => 'obrigatório',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 2,
                'nome' => 'api/logout',
                'method' => 'GET',
                'descricao' => 'Api que faz logout do usuário',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => true,
                'grupo' => 'obrigatório',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 3,
                'nome' => 'api/usuario/info',
                'method' => 'GET',
                'descricao' => 'Configurações do usuário',
                'destaque' => false,
                'nome_amigavel' => 'Configurações do Usuário',
                'obrigatorio' => true,
                'grupo' => 'obrigatório',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 4,
                'nome' => 'api/atualizar-senha',
                'method' => 'GET',
                'descricao' => 'Tela para usuário atualizar sua senha',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => true,
                'grupo' => 'obrigatório',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 5,
                'nome' => 'api/atualizar-senha',
                'method' => 'POST',
                'descricao' => 'Atualizar senha do usuário logado',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => true,
                'grupo' => 'obrigatório',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 6,
                'nome' => '/home',
                'method' => 'GET',
                'descricao' => 'Tela inicial do usuário logado',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => true,
                'grupo' => 'obrigatório',
                'rota_front' => true,
                'log_acesso' => false,
            ],
            [
                'id' => 7,
                'nome' => '/configuracoes',
                'method' => 'GET',
                'descricao' => 'Tela para usuário atualizar seus dados e senha',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => true,
                'grupo' => 'obrigatório',
                'rota_front' => true,
                'log_acesso' => false,
            ],
            [
                'id' => 8,
                'nome' => 'api/info',
                'method' => 'GET',
                'descricao' => 'Informações do usuário logado (usado na autenticação para baixar menu e rotas)',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => true,
                'grupo' => 'obrigatório',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 9,
                'nome' => 'api/admin/usuario',
                'method' => 'POST',
                'descricao' => 'Ajax que cria um novo usuário',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => false,
                'grupo' => 'Usuário',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 10,
                'nome' => '/admin/usuario',
                'method' => 'GET',
                'descricao' => 'Administração de Usuários',
                'destaque' => true,
                'nome_amigavel' => 'Pesquisar Usuário',
                'obrigatorio' => false,
                'grupo' => 'Usuário',
                'rota_front' => true,
                'log_acesso' => false,
            ],
            [
                'id' => 11,
                'nome' => 'api/admin/usuario/grid',
                'method' => 'GET',
                'descricao' => 'Ajax que carrega lista de usuários',
                'destaque' => false,
                'nome_amigavel' => 'Ajax grid de usuários',
                'obrigatorio' => false,
                'grupo' => 'Usuário',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 12,
                'nome' => '/admin/usuario/create',
                'method' => 'GET',
                'descricao' => 'Tela de cadastro de usuário',
                'destaque' => true,
                'nome_amigavel' => 'Cadastrar Usuário',
                'obrigatorio' => false,
                'grupo' => 'Usuário',
                'rota_front' => true,
                'log_acesso' => false,
            ],
            [
                'id' => 13,
                'nome' => 'api/admin/usuario',
                'method' => 'GET',
                'descricao' => 'Carrega combo de perfis na pesquisa de usuário',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => false,
                'grupo' => 'Usuário',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 14,
                'nome' => '/admin/usuario/{usuario}/edit',
                'method' => 'GET',
                'descricao' => 'Tela de edição de usuário',
                'destaque' => true,
                'nome_amigavel' => 'Editar Usuário',
                'obrigatorio' => false,
                'grupo' => 'Usuário',
                'rota_front' => true,
                'log_acesso' => false,
            ],
            [
                'id' => 15,
                'nome' => 'api/admin/usuario/{usuario}',
                'method' => 'PUT',
                'descricao' => 'Ajax que atualiza um usuário',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => false,
                'grupo' => 'Usuário',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 16,
                'nome' => 'api/admin/usuario/{usuario}',
                'method' => 'DELETE',
                'descricao' => 'Excluir um usuário',
                'destaque' => true,
                'nome_amigavel' => 'Excluir usuário',
                'obrigatorio' => false,
                'grupo' => 'Usuário',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 17,
                'nome' => '/admin/perfil',
                'method' => 'GET',
                'descricao' => 'Administração de Perfis',
                'destaque' => true,
                'nome_amigavel' => 'Pesquisar Perfil',
                'obrigatorio' => false,
                'grupo' => 'Perfil',
                'rota_front' => true,
                'log_acesso' => false,
            ],
            [
                'id' => 18,
                'nome' => 'api/perfil/grid',
                'method' => 'GET',
                'descricao' => 'Administração de Perfis',
                'destaque' => false,
                'nome_amigavel' => 'Ajax que lista perfis',
                'obrigatorio' => false,
                'grupo' => 'Perfil',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 19,
                'nome' => '/admin/perfil/create',
                'method' => 'GET',
                'descricao' => 'Tela de cadastro de perfil',
                'destaque' => true,
                'nome_amigavel' => 'Cadastrar Perfil',
                'obrigatorio' => false,
                'grupo' => 'Perfil',
                'rota_front' => true,
                'log_acesso' => false,
            ],
            [
                'id' => 20,
                'nome' => 'api/perfil',
                'method' => 'POST',
                'descricao' => 'Ajax que salva um Perfil',
                'destaque' => false,
                'nome_amigavel' => 'Ajax que lista perfis',
                'obrigatorio' => false,
                'grupo' => 'Perfil',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 21,
                'nome' => 'api/perfil/create',
                'method' => 'GET',
                'descricao' => 'Ajax que carrega dados de cadastro de perfil',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => false,
                'grupo' => 'Perfil',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 22,
                'nome' => '/admin/perfil/{id}/edit',
                'method' => 'GET',
                'descricao' => 'Tela de edição de perfil',
                'destaque' => true,
                'nome_amigavel' => 'Editar Perfil',
                'obrigatorio' => false,
                'grupo' => 'Perfil',
                'rota_front' => true,
                'log_acesso' => false,
            ],
            [
                'id' => 23,
                'nome' => 'api/perfil/{perfil}/edit',
                'method' => 'GET',
                'descricao' => 'Ajax que atualiza um perfil',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => false,
                'grupo' => 'Perfil',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 24,
                'nome' => 'api/perfil/{perfil}',
                'method' => 'PUT',
                'descricao' => 'Ajax que atualiza um perfil',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => false,
                'grupo' => 'Perfil',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 25,
                'nome' => 'api/perfil/{perfil}',
                'method' => 'DELETE',
                'descricao' => 'Exclui um perfil',
                'destaque' => true,
                'nome_amigavel' => 'Excluir perfil',
                'obrigatorio' => false,
                'grupo' => 'Perfil',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 26,
                'nome' => '/seguranca/acoes',
                'method' => 'GET',
                'descricao' => 'Tela de pesquisa de ação',
                'destaque' => true,
                'nome_amigavel' => 'Pesquisar Ação',
                'obrigatorio' => false,
                'grupo' => 'Ação',
                'rota_front' => true,
                'log_acesso' => false,
            ],
            [
                'id' => 27,
                'nome' => 'api/acao/grid',
                'method' => 'GET',
                'descricao' => 'Ajax cadastro de ação',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => false,
                'grupo' => 'Ação',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 28,
                'nome' => '/seguranca/acoes/create',
                'method' => 'GET',
                'descricao' => 'Tela de cadastro de ação',
                'destaque' => true,
                'nome_amigavel' => 'Cadastrar Ação',
                'obrigatorio' => false,
                'grupo' => 'Ação',
                'rota_front' => true,
                'log_acesso' => false,
            ],
            [
                'id' => 29,
                'nome' => 'api/acao/create',
                'method' => 'GET',
                'descricao' => 'Ajax que carrega informações na tela de cadastro de ação',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => false,
                'grupo' => 'Ação',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 30,
                'nome' => 'api/acao',
                'method' => 'POST',
                'descricao' => 'Ajax que cadastra uma ação',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => false,
                'grupo' => 'Ação',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 31,
                'nome' => '/seguranca/acoes/{id}/edit',
                'method' => 'GET',
                'descricao' => 'Tela de edição de Ação',
                'destaque' => true,
                'nome_amigavel' => 'Editar Ação',
                'obrigatorio' => false,
                'grupo' => 'Ação',
                'rota_front' => true,
                'log_acesso' => false,
            ],
            [
                'id' => 32,
                'nome' => 'api/acao/{acao}/edit',
                'method' => 'GET',
                'descricao' => 'Ajax que carrega informações na tela de alteração de ação',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => false,
                'grupo' => 'Ação',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 33,
                'nome' => 'api/acao/{acao}',
                'method' => 'PUT',
                'descricao' => 'Ajax que carrega uma ação',
                'destaque' => false,
                'nome_amigavel' => 'Alterar Ação',
                'obrigatorio' => false,
                'grupo' => 'Ação',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 34,
                'nome' => 'api/acao/{acao}',
                'method' => 'DELETE',
                'descricao' => 'Excluir ação',
                'destaque' => true,
                'nome_amigavel' => 'Excluir Ação',
                'obrigatorio' => false,
                'grupo' => 'Ação',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 35,
                'nome' => 'api/admin/usuario/info',
                'method' => 'GET',
                'descricao' => 'Ajax que carrega informações na tela de cadastro de usuário',
                'destaque' => false,
                'nome_amigavel' => null,
                'obrigatorio' => false,
                'grupo' => 'Usuário',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 36,
                'nome' => 'api/usuario/configuracoes',
                'method' => 'PATCH',
                'descricao' => 'Configurações do usuário',
                'destaque' => false,
                'nome_amigavel' => 'Configurações do Usuário',
                'obrigatorio' => true,
                'grupo' => 'obrigatório',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 37,
                'nome' => 'api/usuario/configuracoes',
                'method' => 'GET',
                'descricao' => 'Configurações do usuário',
                'destaque' => false,
                'nome_amigavel' => 'Configurações do Usuário',
                'obrigatorio' => true,
                'grupo' => 'obrigatório',
                'rota_front' => false,
                'log_acesso' => false,
            ],
            [
                'id' => 38,
                'nome' => 'api/configuracoes/senha',
                'method' => 'PUT',
                'descricao' => 'Ajax que atualiza a senha do usuário',
                'destaque' => false,
                'nome_amigavel' => 'Configurações do Usuário',
                'obrigatorio' => true,
                'grupo' => 'obrigatório',
                'rota_front' => false,
                'log_acesso' => false,
            ],
        ];

        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('seg_acao')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        SegAcao::insert($items);

        //pulando sequence para o número mil para deixar reservado para o segurança
        //Versão MySQL
        DB::statement('ALTER TABLE seg_acao AUTO_INCREMENT = 1000');
        
        //Versão PostgreSQL
        //DB::statement("select setval('seg_acao_id_seq', 1000, true);");
    }
}
