<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SegAcaoLocalSeeder extends Seeder
{
    public function run(): void
    {
        $agora = date('Y-m-d H:i:s');

        $items = [
            [
                'id' => 50,
                'nome' => 'cartao',
                'method' => 'get',
                'descricao' => 'Pesquisar Cartões',
                'destaque' => 1,
                'nome_amigavel' => 'Pesquisar Cartões',
                'obrigatorio' => 0,
                'grupo' => 'Cartão',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 51,
                'nome' => 'cartao/create',
                'method' => 'get',
                'descricao' => 'Cadastrar Cartão',
                'destaque' => 1,
                'nome_amigavel' => 'Cadastrar Cartão',
                'obrigatorio' => 0,
                'grupo' => 'Cartão',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 52,
                'nome' => 'cartao/store',
                'method' => 'post',
                'descricao' => 'Ajax Salvar cartão',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Cartão',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 53,
                'nome' => 'cartao/edit/{codigo}',
                'method' => 'get',
                'descricao' => 'Editar Cartão',
                'destaque' => 1,
                'nome_amigavel' => 'Editar Cartão',
                'obrigatorio' => 0,
                'grupo' => 'Cartão',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 54,
                'nome' => 'cartao/bloqueia-desbloqueia',
                'method' => 'get',
                'descricao' => 'Bloquear e Desbloquear Cartão do Cliente',
                'destaque' => 1,
                'nome_amigavel' => 'Bloquear e Desbloquear Cartão do Cliente',
                'obrigatorio' => 0,
                'grupo' => 'Cartão Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 55,
                'nome' => 'cartao-cliente',
                'method' => 'get',
                'descricao' => 'Pesquisar Cartão do Cliente',
                'destaque' => 1,
                'nome_amigavel' => 'Pesquisar Cartão do Cliente',
                'obrigatorio' => 0,
                'grupo' => 'Cartão Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 56,
                'nome' => 'cartao-cliente/pesquisar',
                'method' => 'get',
                'descricao' => '',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Cartão Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 57,
                'nome' => 'cartao-cliente/edit/{id}',
                'method' => 'get',
                'descricao' => 'Editar Entrada do Cliente',
                'destaque' => 1,
                'nome_amigavel' => 'Editar Entrada do Cliente',
                'obrigatorio' => 0,
                'grupo' => 'Cartão Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 58,
                'nome' => 'cartao-cliente/create/{codigo}',
                'method' => 'get',
                'descricao' => 'Cadastrar Entrada do Cliente',
                'destaque' => 1,
                'nome_amigavel' => 'Cadastrar Entrada do Cliente',
                'obrigatorio' => 0,
                'grupo' => 'Cartão Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 59,
                'nome' => 'cartao-cliente/store',
                'method' => 'post',
                'descricao' => 'Ajax Salvar Entrada Cliente',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Cartão Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 60,
                'nome' => 'cartao-cliente/leitor',
                'method' => 'get',
                'descricao' => 'Adicionar Crédito',
                'destaque' => 1,
                'nome_amigavel' => 'Adicionar Crédito',
                'obrigatorio' => 0,
                'grupo' => 'Cartão Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 61,
                'nome' => 'cartao-cliente/add-credito/{cartao}',
                'method' => 'get',
                'descricao' => 'Tela Adicionar  Crédito',
                'destaque' => 0,
                'nome_amigavel' => 'Tela Adicionar  Crédito',
                'obrigatorio' => 0,
                'grupo' => 'Adicionar Crédito',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 62,
                'nome' => 'cartao-cliente/salvar-credito',
                'method' => 'post',
                'descricao' => 'Salvar Crédito Ajax',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Adicionar Crédito',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 63,
                'nome' => 'cartao-cliente/confirma-credito',
                'method' => 'get',
                'descricao' => 'Confirmação de Crédito',
                'destaque' => 0,
                'nome_amigavel' => 'Confirmação de Crédito',
                'obrigatorio' => 0,
                'grupo' => 'Adicionar Crédito',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 64,
                'nome' => 'cardapio',
                'method' => 'get',
                'descricao' => 'Ver Cardápios Admin',
                'destaque' => 1,
                'nome_amigavel' => 'Ver Cardápios Admin',
                'obrigatorio' => 0,
                'grupo' => 'Cardápio',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 65,
                'nome' => 'cardapio/ver-foto/{id}',
                'method' => 'get',
                'descricao' => 'Ver Foto',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Cardápio',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 66,
                'nome' => 'cardapio/create',
                'method' => 'get',
                'descricao' => 'Cadastrar Cardápio Admin',
                'destaque' => 1,
                'nome_amigavel' => 'Cadastrar Cardápio Admin',
                'obrigatorio' => 0,
                'grupo' => 'Cardápio',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 67,
                'nome' => 'cardapio/store',
                'method' => 'post',
                'descricao' => 'Salvar / Alterar Cardápio item',
                'destaque' => 1,
                'nome_amigavel' => 'Salvar / Alterar Cardápio item',
                'obrigatorio' => 0,
                'grupo' => 'Cardápio',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 68,
                'nome' => 'cardapio/edit/{id}',
                'method' => 'get',
                'descricao' => 'Tela Editar Cardápio Adm',
                'destaque' => 1,
                'nome_amigavel' => 'Tela Editar Cardápio Adm',
                'obrigatorio' => 0,
                'grupo' => 'Cardápio',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 69,
                'nome' => 'cardapio/ver-thumb/{id}',
                'method' => 'get',
                'descricao' => 'Ver Thumb',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Cardápio',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 70,
                'nome' => 'pedido/cardapio/1',
                'method' => 'get',
                'descricao' => 'Cardápio PDV',
                'destaque' => 1,
                'nome_amigavel' => 'Cardápio PDV',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 71,
                'nome' => 'pedido/cardapio/item/{id}',
                'method' => 'get',
                'descricao' => 'Editar Item do Pedido',
                'destaque' => 0,
                'nome_amigavel' => 'Editar Item do Pedido',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 72,
                'nome' => 'pedido/cardapio/add-pedido-cliente',
                'method' => 'post',
                'descricao' => 'Ajax adicionar pedido',
                'destaque' => 0,
                'nome_amigavel' => 'Ajax adicionar pedido',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 73,
                'nome' => 'pedido/finalizar/leitor',
                'method' => 'get',
                'descricao' => NULL,
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 74,
                'nome' => 'pedido/finalizar/{codigo}',
                'method' => 'get',
                'descricao' => NULL,
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 75,
                'nome' => 'pedido/cardapios',
                'method' => 'get',
                'descricao' => 'Cardápios',
                'destaque' => 1,
                'nome_amigavel' => 'Cardápios',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 76,
                'nome' => 'pedido/confirmar-pedido',
                'method' => 'get',
                'descricao' => 'Confirmar Crédito no Cartão',
                'destaque' => 0,
                'nome_amigavel' => 'Confirmar Crédito no Cartão',
                'obrigatorio' => 0,
                'grupo' => 'Cartão Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 77,
                'nome' => 'pedido/historico-pedidos/{mesa}',
                'method' => 'get',
                'descricao' => 'Histórico de Pedidos',
                'destaque' => 1,
                'nome_amigavel' => 'Pedido',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 78,
                'nome' => 'pedido/meus-pedidos',
                'method' => 'get',
                'descricao' => 'Meus Pedidos',
                'destaque' => 1,
                'nome_amigavel' => 'Meus Pedidos',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 79,
                'nome' => 'pedido/confirmar-cancelamento/{item}/{id_tipo_cardapio}',
                'method' => 'get',
                'descricao' => 'Cancelar ítem do pedido',
                'destaque' => 1,
                'nome_amigavel' => 'Cancelar ítem do pedido',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 80,
                'nome' => 'pedido/cancelar/{item}/{id_tipo_cardapio}',
                'method' => 'post',
                'descricao' => NULL,
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 81,
                'nome' => 'cartao-cliente/bloqueia-desbloqueia',
                'method' => 'get',
                'descricao' => NULL,
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Cartão Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 82,
                'nome' => 'cartao-cliente/localizar-cartao/{codigo}',
                'method' => 'get',
                'descricao' => NULL,
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Cartão Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 83,
                'nome' => 'cozinha/monitor',
                'method' => 'get',
                'descricao' => 'Monitor de Cozinha',
                'destaque' => 1,
                'nome_amigavel' => 'Monitor de Cozinha',
                'obrigatorio' => 0,
                'grupo' => 'Cozinha',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 84,
                'nome' => 'cozinha/pedido-pronto/{id_pedido}',
                'method' => 'get',
                'descricao' => NULL,
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Cozinha',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 85,
                'nome' => 'pedido/historico-pedido/{id_pedido}/{tipo}',
                'method' => 'get',
                'descricao' => 'Histórico Pedido',
                'destaque' => 1,
                'nome_amigavel' => 'Histórico Pedido',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 86,
                'nome' => 'pedido/confirmar-entrega/{id_pedido}/{tipo}',
                'method' => 'get',
                'descricao' => 'Entregar Pedido',
                'destaque' => 1,
                'nome_amigavel' => 'Entregar Pedido',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 87,
                'nome' => 'pedido/salvar-entrega/{id_pedido}/{tipo}',
                'method' => 'get',
                'descricao' => NULL,
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 88,
                'nome' => 'relatorio/resumo/pdv',
                'method' => 'get',
                'descricao' => 'Faturamento  dos PDVs',
                'destaque' => 1,
                'nome_amigavel' => 'Faturamento  dos PDVs',
                'obrigatorio' => 0,
                'grupo' => 'Relatório',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 89,
                'nome' => 'relatorio/detalhado/pdv',
                'method' => 'get',
                'descricao' => 'Faturamento dos PDVs por Promotor',
                'destaque' => 1,
                'nome_amigavel' => 'Faturamento dos PDVs por Promotor',
                'obrigatorio' => 0,
                'grupo' => 'Relatório',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 90,
                'nome' => 'relatorios',
                'method' => 'get',
                'descricao' => 'Menu Relatórios Gerente',
                'destaque' => 1,
                'nome_amigavel' => 'Menu Relatórios Gerente',
                'obrigatorio' => 0,
                'grupo' => 'Relatório',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 91,
                'nome' => 'relatorio/taxa-servico',
                'method' => 'get',
                'descricao' => 'Comissão do Promotor',
                'destaque' => 1,
                'nome_amigavel' => 'Comissão do Promotor',
                'obrigatorio' => 0,
                'grupo' => 'Relatório',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 94,
                'nome' => 'cliente/pedidos',
                'method' => 'get',
                'descricao' => 'Pedidos do Cliente',
                'destaque' => 1,
                'nome_amigavel' => 'Pedidos do Cliente',
                'obrigatorio' => 0,
                'grupo' => 'Clinete',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 95,
                'nome' => 'cardapio/salvar-categoria',
                'method' => 'post',
                'descricao' => NULL,
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Cardápio',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 96,
                'nome' => 'relatorio/fechamento-caixa',
                'method' => 'get',
                'descricao' => 'Fechamento da Caixa',
                'destaque' => 1,
                'nome_amigavel' => 'Fechamento da Caixa',
                'obrigatorio' => 0,
                'grupo' => 'Relatório',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 97,
                'nome' => 'pedido/visualizacao-gerente',
                'method' => 'get',
                'descricao' => 'Ver todos os pedidos (Gerente)',
                'destaque' => 1,
                'nome_amigavel' => 'Ver todos os pedidos (Gerente)',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 98,
                'nome' => 'pedido/historico-pedido-gerente/{id_pedido}',
                'method' => 'get',
                'descricao' => 'Histórico Pedido (Gerente)',
                'destaque' => 1,
                'nome_amigavel' => 'Histórico Pedido (Gerente)',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 99,
                'nome' => 'pedido/cancelar-gerente/{item}/{id_tipo_cardapio}',
                'method' => 'post',
                'descricao' => NULL,
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 100,
                'nome' => 'pedido/confirmar-cancelamento-gerente/{item}/{id_tipo_cardapio}',
                'method' => 'get',
                'descricao' => 'Cancelar ítem do pedido (Gerente)',
                'destaque' => 1,
                'nome_amigavel' => 'Cancelar ítem do pedido (Gerente)',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 101,
                'nome' => 'pedido/confirmar-entrega-gerente/{id_pedido}/{tipo}',
                'method' => 'get',
                'descricao' => 'Entregar Pedido (Gerente)',
                'destaque' => 1,
                'nome_amigavel' => 'Entregar Pedido (Gerente)',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 102,
                'nome' => 'pedido/salvar-entrega-gerente/{id_pedido}/{tipo}',
                'method' => 'get',
                'descricao' => NULL,
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 103,
                'nome' => 'relatorio/fechamento-conta/{codigo}',
                'method' => 'get',
                'descricao' => 'Fechamento de Conta',
                'destaque' => 1,
                'nome_amigavel' => 'Fechamento de Conta',
                'obrigatorio' => 0,
                'grupo' => 'Relatório',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 104,
                'nome' => 'relatorio/consultar-pedidos',
                'method' => 'get',
                'descricao' => 'Consultar Pedidos',
                'destaque' => 1,
                'nome_amigavel' => 'Consultar Pedidos',
                'obrigatorio' => 0,
                'grupo' => 'Relatório',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 105,
                'nome' => 'cardapio/ativar-item',
                'method' => 'get',
                'descricao' => 'Ativar Item do Cardapio',
                'destaque' => 1,
                'nome_amigavel' => 'Ativar Item do Cardapio',
                'obrigatorio' => 0,
                'grupo' => 'Cardápio',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 106,
                'nome' => 'cardapio/inativar-item',
                'method' => 'get',
                'descricao' => 'Inativar Item do Cardapio',
                'destaque' => 1,
                'nome_amigavel' => 'Inativar Item do Cardapio',
                'obrigatorio' => 0,
                'grupo' => 'Cardápio',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 108,
                'nome' => 'pedido/confirmar-cancelamento-gerente2/{item}/{codigo}',
                'method' => 'get',
                'descricao' => 'Cancelar Item | Consulta Pedido',
                'destaque' => 1,
                'nome_amigavel' => 'Cancelar Item | Consulta Pedido',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 109,
                'nome' => 'pedido/cancelar-gerente2/{item}/{codigo}',
                'method' => 'get',
                'descricao' => 'Cancelar Item Ajax',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 110,
                'nome' => 'cartao-cliente/devolver-cartao',
                'method' => 'get',
                'descricao' => 'Devolver Cartão',
                'destaque' => 1,
                'nome_amigavel' => 'Devolver Cartão',
                'obrigatorio' => 0,
                'grupo' => 'Cartão Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 111,
                'nome' => 'cartao-cliente/transferir-credito/{codigo}',
                'method' => 'get',
                'descricao' => 'Transferir Crédito Outro Cartão',
                'destaque' => 1,
                'nome_amigavel' => 'Transferir Crédito Outro Cartão',
                'obrigatorio' => 0,
                'grupo' => 'Cartão Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 112,
                'nome' => 'cozinha/confirma/{id_pedido}',
                'method' => 'get',
                'descricao' => 'Confirmar Pedido Pronto',
                'destaque' => 0,
                'nome_amigavel' => 'Confirmar Pedido Pronto',
                'obrigatorio' => 0,
                'grupo' => 'Cozinha',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 113,
                'nome' => 'cartao-cliente/zerar-cartao',
                'method' => 'get',
                'descricao' => 'Zerar Cartão do Cliente',
                'destaque' => 1,
                'nome_amigavel' => 'Zerar Cartão do Cliente',
                'obrigatorio' => 0,
                'grupo' => 'Cartão Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 114,
                'nome' => 'cardapio/tipo-cardapio',
                'method' => 'get',
                'descricao' => 'Gerenciar Tipos de Cardápio',
                'destaque' => 1,
                'nome_amigavel' => 'Gerenciar Tipos de Cardápio',
                'obrigatorio' => 0,
                'grupo' => 'Cardápio',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 115,
                'nome' => 'cardapio/salvar-tipo-cardapio',
                'method' => 'get',
                'descricao' => NULL,
                'destaque' => 0,
                'nome_amigavel' => 'Cadastrar Tipo de Cardápio',
                'obrigatorio' => 0,
                'grupo' => NULL,
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 116,
                'nome' => 'cardapio/tipo-cardapio/thumb/{id}',
                'method' => 'get',
                'descricao' => 'Ver Thumb Tipo de Cardápio',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => NULL,
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 117,
                'nome' => 'cartao/gerar-cartoes',
                'method' => 'get',
                'descricao' => '',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => NULL,
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 118,
                'nome' => 'cartao/gerar-qrcode/{id}',
                'method' => 'get',
                'descricao' => NULL,
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => NULL,
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 119,
                'nome' => 'relatorio/devolucao-cartoes',
                'method' => 'get',
                'descricao' => 'Relatório de Devolução de Cartões',
                'destaque' => 1,
                'nome_amigavel' => 'Relatório de Devolução de Cartões',
                'obrigatorio' => 0,
                'grupo' => 'Relatório',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 120,
                'nome' => 'relatorio/cancelamento',
                'method' => 'get',
                'descricao' => 'Relatório de Cancelamento',
                'destaque' => 1,
                'nome_amigavel' => 'Relatório de Cancelamento',
                'obrigatorio' => 0,
                'grupo' => 'Relatório',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 121,
                'nome' => 'cartao-cliente/leitor-transferencia',
                'method' => 'get',
                'descricao' => 'Transferir Crédito',
                'destaque' => 1,
                'nome_amigavel' => 'Transferir Crédito',
                'obrigatorio' => 0,
                'grupo' => 'Transferência',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 122,
                'nome' => 'cartao-cliente/dados-transferencia/{codigo}',
                'method' => 'get',
                'descricao' => 'Dados da Transferência',
                'destaque' => 0,
                'nome_amigavel' => 'Dados da Transferência',
                'obrigatorio' => 0,
                'grupo' => 'Transferência',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 123,
                'nome' => 'cartao-cliente/salvar-transferencia',
                'method' => 'post',
                'descricao' => 'Salvar Transferência',
                'destaque' => 0,
                'nome_amigavel' => 'Salvar Transferência',
                'obrigatorio' => 0,
                'grupo' => 'Transferência',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 124,
                'nome' => 'cartao-cliente/confirma-transferencia',
                'method' => 'get',
                'descricao' => 'Confirmar transferencia',
                'destaque' => 0,
                'nome_amigavel' => 'Confirmar Transferência',
                'obrigatorio' => 0,
                'grupo' => 'Transferência',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 125,
                'nome' => 'estoque',
                'method' => 'get',
                'descricao' => 'Gerenciador de Estoque',
                'destaque' => 1,
                'nome_amigavel' => 'Gerenciador de Estoque',
                'obrigatorio' => 0,
                'grupo' => 'Estoque',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 126,
                'nome' => 'estoque/get-estoque-item/{id}',
                'method' => 'get',
                'descricao' => 'Get Dados do Estoque do Item',
                'destaque' => 0,
                'nome_amigavel' => 'Get Dados do Estoque do Item',
                'obrigatorio' => 0,
                'grupo' => 'Estoque',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 127,
                'nome' => 'estoque/store',
                'method' => 'post',
                'descricao' => 'Salvar Item no Estoque',
                'destaque' => 0,
                'nome_amigavel' => 'Salvar Item no Estoque',
                'obrigatorio' => 0,
                'grupo' => 'Estoque',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 128,
                'nome' => 'estoque/relatorio',
                'method' => 'get',
                'descricao' => 'Relatório do Estoque',
                'destaque' => 1,
                'nome_amigavel' => 'Relatório do Estoque',
                'obrigatorio' => 0,
                'grupo' => 'Estoque',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 129,
                'nome' => 'estoque/resumo',
                'method' => 'get',
                'descricao' => 'Resumo do Estoque',
                'destaque' => 1,
                'nome_amigavel' => 'Resumo do Estoque',
                'obrigatorio' => 0,
                'grupo' => 'Estoque',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 130,
                'nome' => 'cardapio/salvar-produto',
                'method' => 'get',
                'descricao' => 'Salvar Produto Ajax',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'Cardápio',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 132,
                'nome' => 'estoque/detalhes-item',
                'method' => 'get',
                'descricao' => 'Detalhes do Item no Estoque',
                'destaque' => 0,
                'nome_amigavel' => 'Detalhes do Item no Estoque',
                'obrigatorio' => 0,
                'grupo' => 'Estoque',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 133,
                'nome' => 'estoque/detalhamento-item',
                'method' => 'get',
                'descricao' => 'Detalhamento no Estoque do Produto',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => 'estoque',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 136,
                'nome' => 'cliente/create',
                'method' => 'get',
                'descricao' => 'Tela Cadastrar Cliente',
                'destaque' => 1,
                'nome_amigavel' => 'Tela Cadastrar Cliente',
                'obrigatorio' => 0,
                'grupo' => 'Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 137,
                'nome' => 'cliente/list/{texto?}',
                'method' => 'get',
                'descricao' => 'Tela Pesquisa de Cliente',
                'destaque' => 1,
                'nome_amigavel' => 'Tela Pesquisa de Clientes',
                'obrigatorio' => 0,
                'grupo' => 'Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 138,
                'nome' => 'cliente/edit/{id}',
                'method' => 'get',
                'descricao' => 'Tela Editar Cliente',
                'destaque' => 1,
                'nome_amigavel' => 'Tela Editar Cliente',
                'obrigatorio' => 0,
                'grupo' => 'Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 139,
                'nome' => 'cliente/store',
                'method' => 'post',
                'descricao' => 'Salvar Novo Cliente',
                'destaque' => 0,
                'nome_amigavel' => 'Salvar Novo Cliente',
                'obrigatorio' => 0,
                'grupo' => 'Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 141,
                'nome' => 'dependente/store',
                'method' => 'post',
                'descricao' => 'Salvar Dependênte',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => NULL,
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 142,
                'nome' => 'dependente/edit/{id}',
                'method' => 'get',
                'descricao' => 'Editar Dependente',
                'destaque' => 0,
                'nome_amigavel' => 'Editar Dependente',
                'obrigatorio' => 0,
                'grupo' => 'Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 143,
                'nome' => 'dependente/ativar/{id}',
                'method' => 'post',
                'descricao' => 'Ativar Dependente',
                'destaque' => 1,
                'nome_amigavel' => 'Ativar Dependente',
                'obrigatorio' => 0,
                'grupo' => 'Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 144,
                'nome' => 'dependente/inativar/{id}',
                'method' => 'post',
                'descricao' => 'Inativar Dependente',
                'destaque' => 1,
                'nome_amigavel' => 'Inativar Dependente',
                'obrigatorio' => 0,
                'grupo' => 'Cliente',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 145,
                'nome' => 'financeiro',
                'method' => 'get',
                'descricao' => 'Tela Pesquisa Financeiro',
                'destaque' => 1,
                'nome_amigavel' => 'Tela Pesquisa Financeiro',
                'obrigatorio' => 0,
                'grupo' => 'financeiro',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 146,
                'nome' => 'financeiro/historico',
                'method' => 'get',
                'descricao' => 'Tela Histórico de Pagamento',
                'destaque' => 1,
                'nome_amigavel' => 'Tela Histórico de Pagamento',
                'obrigatorio' => 0,
                'grupo' => 'financeiro',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 147,
                'nome' => 'financeiro/store',
                'method' => 'post',
                'descricao' => 'Salvar Pagamento',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => NULL,
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 148,
                'nome' => 'financeiro/create/{id_cliente}',
                'method' => 'get',
                'descricao' => 'Tela Registrar Pagamento',
                'destaque' => 1,
                'nome_amigavel' => 'Tela Registrar Pagamento',
                'obrigatorio' => 0,
                'grupo' => 'financeiro',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 149,
                'nome' => 'financeiro/edit/{id}',
                'method' => 'get',
                'descricao' => 'Tela Registrar Pagamento',
                'destaque' => 1,
                'nome_amigavel' => 'Tela Registrar Pagamento',
                'obrigatorio' => 0,
                'grupo' => 'financeiro',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 150,
                'nome' => 'financeiro/remove',
                'method' => 'post',
                'descricao' => 'Remover Pagamento',
                'destaque' => 1,
                'nome_amigavel' => 'Remover Pagamento',
                'obrigatorio' => 0,
                'grupo' => 'financeiro',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 151,
                'nome' => 'portaria/validar-entrada',
                'method' => 'get',
                'descricao' => 'Validar Entrada do Cliente',
                'destaque' => 1,
                'nome_amigavel' => 'Validar Entrada do Cliente',
                'obrigatorio' => 0,
                'grupo' => 'portaria',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 152,
                'nome' => 'portaria',
                'method' => 'get',
                'descricao' => 'Tela de Portaria do Aluno',
                'destaque' => 1,
                'nome_amigavel' => 'Tela de Portaria do Aluno',
                'obrigatorio' => 0,
                'grupo' => 'portaria',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 153,
                'nome' => 'financeiro/relatorio-pagamentos',
                'method' => 'get',
                'descricao' => 'Relatório de Pagamentos',
                'destaque' => 1,
                'nome_amigavel' => 'Relatório de Pagamentos',
                'obrigatorio' => 0,
                'grupo' => 'financeiro',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 154,
                'nome' => 'financeiro/relatorio-pagamentos-atraso',
                'method' => 'get',
                'descricao' => 'Relatório de Pagamentos em Atraso',
                'destaque' => 1,
                'nome_amigavel' => 'Relatório de Pagamentos em Atraso',
                'obrigatorio' => 0,
                'grupo' => 'financeiro',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 155,
                'nome' => 'cardapio/delete/{id}',
                'method' => 'post',
                'descricao' => 'Remover Cardapio (PDV)',
                'destaque' => 1,
                'nome_amigavel' => 'Remover Cardapio (PDV)',
                'obrigatorio' => 0,
                'grupo' => 'Cardápio',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 156,
                'nome' => 'cardapio/ativar-cardapio',
                'method' => 'post',
                'descricao' => 'Ativar Cardapio',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => NULL,
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 157,
                'nome' => 'cardapio/inativar-cardapio',
                'method' => 'post',
                'descricao' => 'inativar Cardapio',
                'destaque' => 0,
                'nome_amigavel' => NULL,
                'obrigatorio' => 0,
                'grupo' => NULL,
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 158,
                'nome' => 'relatorio/vendas',
                'method' => 'get',
                'descricao' => 'Relatorio de vendas',
                'destaque' => 1,
                'nome_amigavel' => 'Relatorio de vendas',
                'obrigatorio' => 0,
                'grupo' => 'Relatório',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 159,
                'nome' => 'dashboard',
                'method' => 'get',
                'descricao' => 'Dashboard',
                'destaque' => 1,
                'nome_amigavel' => 'Dashboard',
                'obrigatorio' => 0,
                'grupo' => 'Dashboard',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 160,
                'nome' => 'dashboard/pedidos-por-hora/{data}',
                'method' => 'get',
                'descricao' => 'Ajax Pedidos por Hora',
                'destaque' => 0,
                'nome_amigavel' => 'Ajax Pedidos por Hora',
                'obrigatorio' => 0,
                'grupo' => 'Dashboard',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 161,
                'nome' => 'dashboard/recargas-por-hora/{data}',
                'method' => 'get',
                'descricao' => 'Ajax Recargas por Hora',
                'destaque' => 0,
                'nome_amigavel' => 'Ajax Recargas por Hora',
                'obrigatorio' => 0,
                'grupo' => 'Dashboard',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 165,
                'nome' => 'pedido/cardapio/show/{id_tipo_cardapio}',
                'method' => 'get',
                'descricao' => 'Cardápio para realizar pedido',
                'destaque' => 0,
                'nome_amigavel' => 'Cardápio para realizar pedido',
                'obrigatorio' => 0,
                'grupo' => 'pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 166,
                'nome' => 'pedido/cardapio/remove-item-pedido-cliente',
                'method' => 'get',
                'descricao' => 'Remover Item Pedido na tela de Cardápio',
                'destaque' => 0,
                'nome_amigavel' => 'Remover Item Pedido na tela de Cardápio',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 0,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 167,
                'nome' => 'cliente/cardapio/show/{id_tipo_cardapio}',
                'method' => 'get',
                'descricao' => 'Ver Cardápio Área do Cliente',
                'destaque' => 0,
                'nome_amigavel' => 'Ver Cardápio Área do Cliente',
                'obrigatorio' => 0,
                'grupo' => 'Cliente',
                'log_acesso' => 1,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 168,
                'nome' => 'cliente/cardapio/add-pedido-cliente',
                'method' => 'get',
                'descricao' => 'Adicionar Item',
                'destaque' => 0,
                'nome_amigavel' => 'Adicionar Item',
                'obrigatorio' => 0,
                'grupo' => 'Cliente',
                'log_acesso' => 1,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 169,
                'nome' => 'cliente/cardapio/remove-item-pedido-cliente',
                'method' => 'get',
                'descricao' => 'Excluir Item',
                'destaque' => 0,
                'nome_amigavel' => 'Excluir Item',
                'obrigatorio' => 0,
                'grupo' => 'Cliente',
                'log_acesso' => 1,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 170,
                'nome' => 'cliente/confirmar-pedido',
                'method' => 'get',
                'descricao' => 'Confirmar Pedido',
                'destaque' => 0,
                'nome_amigavel' => 'Confirmar Pedido',
                'obrigatorio' => 0,
                'grupo' => 'Cliente',
                'log_acesso' => 1,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 171,
                'nome' => 'cliente/pedido/finalizar',
                'method' => 'get',
                'descricao' => 'Finalizar Pedido',
                'destaque' => 0,
                'nome_amigavel' => 'Finalizar Pedido',
                'obrigatorio' => 0,
                'grupo' => 'Cliente',
                'log_acesso' => 1,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 172,
                'nome' => 'cliente/meus-pedidos',
                'method' => 'get',
                'descricao' => 'Meus Pedidos',
                'destaque' => 0,
                'nome_amigavel' => 'Meus Pedidos',
                'obrigatorio' => 0,
                'grupo' => 'Cliente',
                'log_acesso' => 1,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 173,
                'nome' => 'cliente/meu-pedido/{pedido_id}',
                'method' => 'get',
                'descricao' => 'Meu Pedido',
                'destaque' => 0,
                'nome_amigavel' => 'Meu Pedido',
                'obrigatorio' => 0,
                'grupo' => 'Cliente',
                'log_acesso' => 1,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 174,
                'nome' => 'cliente/pedido/{pedido_id}/entregue',
                'method' => 'get',
                'descricao' => 'Pedido do Cliente Entregue',
                'destaque' => 0,
                'nome_amigavel' => 'Pedido do Cliente Entregue',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 1,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ],
            [
                'id' => 175,
                'nome' => 'pedido/salvar-entrega/via-qrcode/{id_pedido}',
                'method' => 'get',
                'descricao' => 'Salvar Entrega via QR Code',
                'destaque' => 0,
                'nome_amigavel' => 'Salvar Entrega via QR Code',
                'obrigatorio' => 0,
                'grupo' => 'Pedido',
                'log_acesso' => 1,
                'rota_front' => 0,
                'created_at' => $agora,
                'updated_at' => $agora
            ]
        ];

        DB::table('seg_acao')->insert($items);
    }
}
