services:
    app:
        build:
            args:
                # Não altere o nome de usuário abaixo
                user: ${APP_USUARIO}
                uid: 1000
            context: ./
            dockerfile: docker/php/php.dockerfile
        image: php84
        extra_hosts:
            - host.docker.internal:host-gateway
        container_name: ${APP_NAME:-php}-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./docker/php/.bashrc:/home/${APP_USUARIO}/.bashrc
            - ./docker/php/auth.json:/home/${APP_USUARIO}/.composer/auth.json
        networks:
            - dev

    nginx:
        image: nginx:alpine
        container_name: ${APP_NAME:-web}-nginx
        restart: unless-stopped
        ports:
            - "8001:8000"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - dev
        links:
            - app

    ############################
    # MySQL
    ############################
    db:
        image: mysql:latest
        container_name: ${APP_NAME}-db
        #command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        ports:
            - "${DB_PORT}:${DB_PORT}"
        volumes:
            - mysql-storage:/var/lib/mysql
        networks:
            - dev
networks:
    dev:
        driver: bridge

volumes:
  mysql-storage:
