<?php
namespace GapPay\Seguranca\Request;

use Illuminate\Foundation\Http\FormRequest;

class UsuarioRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'nome' => 'required',
            'email' => 'required|email',
        ];
    }

//    public function validated($key = null, $default = null)
//    {
//        return parent::validated($key, $default); // TODO: Change the autogenerated stub
//    }
}
